20200820 add 9 questions
cloudnativedaysjp/kontest-questions pull request #2
Opened 2020-08-21 01:10 UTC by cyberblack28

ベーシック路線でカテゴリ的にConfigMap,Secret,PV,PVC,Volume.PodSecurityContext,SecurityContext,nodeSelectorで作ってみました。

2020-08-23 06:22 UTC, inductor reviewed
全体的に、`Kubernetesでは、`っていう表現は自明なので不要かなという感じがしました！

2020-08-23 06:22 UTC, inductor commented on 10.yaml
> +    Kubernetesで永続化領域の要求を行うリソースが、PersistentVolumeClaimです。永続化領域の要求が発行されるとKube-Schedulerが保持しているPersistentVolumeから最適なVolumeを割り当てます。
```suggestion
    Kubernetesにおいて、永続化領域の要求を行うリソースがPersistentVolumeClaim(PVC)です。PVCが作成されると、利用可能なPersistentVolume(PV)の中から最適なリソースがPodに割り当てられます。
```

`Kube-Schedulerが保持している` だと、kube-schedulerがPVを所有しているような日本語に見えるのと、問題的には表記する必要がなさそうだったので消してみました。

2020-08-23 06:22 UTC, inductor commented on 10.yaml
> +    800Mi以上のボリュームを要求し、RWXのアクセス モードを指定するcndt-pvcという名前のPersistentVolumeClaimとなるように以下マニフェストファイルを変更してください。
```suggestion
    800Mi以上のボリュームを要求し、RWXのアクセスモードを指定するように以下のマニフェストファイルを変更してください。
```

以下のマニフェスト、とあるので名前やリソース名までは書かなくても良さそうかなと思いました

2020-08-23 06:22 UTC, inductor commented on 11.yaml
> +    KubernetesのPodからcndt-podという名前のPersistentVolumeClaimで要求したPersistentVolumeのVolumeを、cndt-podという名前でmountPath:/usr/share/nginx/htmlにマウントするように以下マニフェストファイルを変更してください。
```suggestion
    cndt-podという名前のPersistentVolumeClaimで要求したPersistentVolumeを、cndt-podという名前でmountPath:/usr/share/nginx/htmlにマウントするように以下マニフェストファイルを変更してください。
```

2020-08-23 06:22 UTC, inductor commented on 11.yaml
> +      creationTimestamp: null
creationTimestamp不要では

2020-08-23 06:22 UTC, inductor commented on 11.yaml
> +        resources: {}
resources不要では

2020-08-23 06:22 UTC, inductor commented on 11.yaml
> +        resources: {}
ditto

2020-08-23 06:22 UTC, inductor commented on 11.yaml
> +      creationTimestamp: null
ditto

2020-08-23 06:22 UTC, inductor commented on 12.yaml
> +    kubernetesでは、ラベル機能を利用して特定のノードにPodを配置する方法があります。
```suggestion
    Kubernetesでは、ラベル機能を利用して特定のノードにPodを配置する方法があります。
```

2020-08-23 06:22 UTC, inductor commented on 13.yaml
> +    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
```suggestion
    emptyDirを使うと、Podに対して一時的なディスク領域をマウントすることができます。この領域は、Podのdeleteと同時に削除されます。
```

一時ディスクってAzureくらいでしか使われないマイナーな表現かなと思います

2020-08-23 06:22 UTC, inductor commented on 13.yaml
> +    tmp-volという名前で/tmpを一時ディスク領域として利用できるように以下マニフェストファイルを変更してください。
```suggestion
    tmp-volという名前で/tmpを一時的なディスク領域として利用できるように、以下マニフェストファイルを変更してください。
```

2020-08-23 06:22 UTC, inductor commented on 14.yaml
> +    Kubernetesでは、Podに対するセキュリティ設定として、PodSecurityContextがあります。
```suggestion
    PodSecurityContextを使うと、Podのアクセス制御や特権に関する設定を変更することができます。
```

2020-08-23 13:00 UTC, cyberblack28 commented on 11.yaml
> +      creationTimestamp: null
-o yaml で書きだしたものをベースとしていますが、無くても問題は無いので消す方向にしましょう。

2020-08-23 13:00 UTC, cyberblack28 commented on 11.yaml
> +        resources: {}
-o yaml で書きだしたものをベースとしていますが、無くても問題は無いので消す方向にしましょう。

2020-08-23 13:00 UTC, cyberblack28 commented on 11.yaml
> +      creationTimestamp: null
-o yaml で書きだしたものをベースとしていますが、無くても問題は無いので消す方向にしましょう。

2020-08-23 13:03 UTC, cyberblack28 commented on 13.yaml
> +    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
一応問題ということで、emptyDirとあからさまに書いてしまうとと思ったので、遠回しな表現にしていました。
ヒント見ればというところもありますが。もしなんかうまい表現が無ければ、そのままemptyDirにしましょうか。

2020-08-23 13:33 UTC, cyberblack28 commented on 11.yaml
> +        resources: {}
-o yaml で書きだしたものをベースとしていますが、無くても問題は無いので消す方向にしましょう。

2020-08-23 14:19 UTC, inductor commented on 11.yaml
> +      creationTimestamp: null
はい、そうだろうと思いましたが、これは人は触らないKubernetesが書き出すフィールドなので不要だと思います。

2020-08-23 14:19 UTC, inductor commented on 11.yaml
> +        resources: {}
はい、そうだろうと思いましたが、これは人は触らないKubernetesが書き出すフィールドなので不要だと思います。

2020-08-23 14:19 UTC, inductor commented on 11.yaml
> +      creationTimestamp: null
はい、そうだろうと思いましたが、これは人は触らないKubernetesが書き出すフィールドなので不要だと思います。

2020-08-23 14:20 UTC, inductor commented on 12.yaml
> +    Kubernetesでは、ラベル機能を利用して特定のノードにPodを配置する方法があります。
全体的にって言ったのはこの辺も含みます（全部指摘するのが途中で面倒になって）

2020-08-23 14:21 UTC, inductor commented on 11.yaml
> +        resources: {}
はい、そうだろうと思いましたが、これは人は触らないKubernetesが書き出すフィールドなので不要だと思います。

2020-08-23 15:17 UTC, cyberblack28 commented on 12.yaml
> +    Kubernetesでは、ラベル機能を利用して特定のノードにPodを配置する方法があります。
了解です。こちらで修正します。

2020-08-23 15:38 UTC, inductor requested changes

2020-08-23 15:38 UTC, inductor commented on 7.yaml
> +    設定情報をKye-Valueとして保存できるリソースがConfigMapです。
```suggestion
    設定情報をKey-Valueとして保存できるリソースがConfigMapです。
```

2020-08-23 19:51 UTC, MasayaAoyama commented on 13.yaml
> +    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
一時ディスク領域（一時的なディスク領域）の表現自体はいいと思います。一般名詞的な使い方なので。
なので遠回しな表現自体には酸性です。

ただ、CSIのInline PVや通常のPod領域も同じように使えそうなので、答えの一意性という面で悩ましいですね…。
Empty Dirとかにしておきますかね。。

2020-08-23 20:07 UTC, MasayaAoyama requested changes

2020-08-23 20:07 UTC, MasayaAoyama commented on 10.yaml
> +    800Mi以上のボリュームを要求し、RWXのアクセスモードを指定するように以下のマニフェストファイルを変更してください。
> 800Mi以上のボリュームを要求し、RWXのアクセスモードを指定するように

複数のノードからReadもWriteも可能なアクセス可能な、800Mi以上のボリュームを要求するように

ですかね。RWXも要求側の要望なので。

2020-08-23 20:07 UTC, MasayaAoyama commented on 11.yaml
> +    cndt-podという名前のPersistentVolumeClaimで要求したPersistentVolumeを、cndt-podという名前でmountPath:/usr/share/nginx/htmlにマウントするように以下マニフェストファイルを変更してください。
cndt-pvcという名前の

の間違いですかね。

2020-08-23 20:07 UTC, MasayaAoyama commented on 12.yaml
> +    arch=amd64のラベルを持つノードにcndt-redisという名前のPodが配置されるように以下マニフェストファイルを変更してください。
arch ラベルは「kubernetes.io/arch」でつけられるようになっているので、合わせましょうか。
または、全く別のラベルにしたほうが良いかなと思いました。

2020-08-23 20:07 UTC, MasayaAoyama commented on 7.yaml
> +      dnsPolicy: ClusterFirst
dnsPolicyとrestartPolicyは不要そうなので消しちゃいますかね

2020-08-23 20:07 UTC, MasayaAoyama commented on 7.yaml
> +    status: {}
statusも同様です

2020-08-23 20:07 UTC, MasayaAoyama commented on 7.yaml
> +    CNDT/Goodというキー/値ペアを含むcndt-configというConfigMapを以下マニフェストファイルのPodから、/config/mapディレクトリをconfig-volumeという名前のボリュームとしてマウントするようにマニフェストファイルを変更してください。
> CNDT/Goodというキー/値ペアを含む

ここらへんは不要な気がしました。
むしろ個別のKeyだけマウントしないよう、複数のキー・値のペアを一括でマウントするように的な文言にしたほう良いと思います。

回答にこういうパターンも出てきちゃうので…
```
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: config-volume
    configMap:
      name: sample-configmap
      items:
      - key: nginx.conf
        path: nginx-sample.conf
```

2020-08-23 20:07 UTC, MasayaAoyama commented on 8.yaml
> +    CNDT/happyというキー/値ペアを含むcndt-secretというSecretを以下マニフェストファイルを変更して、秘密鍵 CNDTの値を後悔する環境変数を追加してください。その際、Pod内部の環境変数名としてCNDT_VARIABLEを使用してください。
後悔＞公開

2020-08-23 20:07 UTC, MasayaAoyama commented on 8.yaml
> +    CNDT/happyというキー/値ペアを含むcndt-secretというSecretを以下マニフェストファイルを変更して、秘密鍵 CNDTの値を後悔する環境変数を追加してください。その際、Pod内部の環境変数名としてCNDT_VARIABLEを使用してください。
こっちは一括で指定されないように、「〜のみを」などと入れておいたほうが良いと思いました。
また、Secret（2つ以上のKeyが書かれてるもので）も問題文に書いておいたほうが良いかもですね。

2020-08-23 20:07 UTC, MasayaAoyama commented on 9.yaml
> +    NFSを使用してcndt-pvという名前のPersistentVolumeを作成し、NFSサーバのIPを192.168.9.8、容量を8Gi、アクセスモードをRXW、Reclaim PolicyをRetain、そのボリュームが当該クラスタのノードの/var/lib/cndtにあることを明示するように以下マニフェストファイルに変更してください。
NFSはクラスタ構成にならないことも多いので、これはちょっとミスリードな気がします。

> 当該クラスタのノードの

2020-08-24 00:26 UTC, inductor commented on 14.yaml
> +      - image: nginx:1.17
どっちでもいいっちゃいいんですが、イメージのバージョン揃ってないのなんとなく気持ち悪いので1.18なのか1.17なのかどっちかにしたいですね（全体の話）

2020-08-24 01:19 UTC, cyberblack28 commented on 13.yaml
> +    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
Empty Dirとしましょう。

2020-08-24 01:20 UTC, cyberblack28 commented on 10.yaml
> +    800Mi以上のボリュームを要求し、RWXのアクセスモードを指定するように以下のマニフェストファイルを変更してください。
その内容で修正します。

2020-08-24 01:20 UTC, cyberblack28 commented on 11.yaml
> +    cndt-podという名前のPersistentVolumeClaimで要求したPersistentVolumeを、cndt-podという名前でmountPath:/usr/share/nginx/htmlにマウントするように以下マニフェストファイルを変更してください。
cndt-pvcで修正します。

2020-08-24 01:20 UTC, cyberblack28 commented on 7.yaml
> +      dnsPolicy: ClusterFirst
横展開して削除します。

2020-08-24 01:20 UTC, cyberblack28 commented on 7.yaml
> +    status: {}
横展開して削除します。

2020-08-24 01:21 UTC, cyberblack28 commented on 7.yaml
> +    CNDT/Goodというキー/値ペアを含むcndt-configというConfigMapを以下マニフェストファイルのPodから、/config/mapディレクトリをconfig-volumeという名前のボリュームとしてマウントするようにマニフェストファイルを変更してください。
文言修正します。

2020-08-24 01:21 UTC, cyberblack28 commented on 8.yaml
> +    CNDT/happyというキー/値ペアを含むcndt-secretというSecretを以下マニフェストファイルを変更して、秘密鍵 CNDTの値を後悔する環境変数を追加してください。その際、Pod内部の環境変数名としてCNDT_VARIABLEを使用してください。
文言修正します。

2020-08-24 01:21 UTC, cyberblack28 commented on 9.yaml
> +    NFSを使用してcndt-pvという名前のPersistentVolumeを作成し、NFSサーバのIPを192.168.9.8、容量を8Gi、アクセスモードをRXW、Reclaim PolicyをRetain、そのボリュームが当該クラスタのノードの/var/lib/cndtにあることを明示するように以下マニフェストファイルに変更してください。
パスを設定するという内容に修正します。

2020-08-24 01:22 UTC, cyberblack28 commented on 14.yaml
> +      - image: nginx:1.17
1.yamlが1.19なので、指定しているものはそれに合わせることにします。

2020-08-24 01:24 UTC, inductor commented on 13.yaml
> +    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
```suggestion
    Empty Dirを使うと、Podに対して一時的なディスク領域をマウントすることができます。この領域は、Podのdeleteと同時に削除されます。
```

こうかな

2020-08-24 01:25 UTC, cyberblack28 commented on 12.yaml
> +    arch=amd64のラベルを持つノードにcndt-redisという名前のPodが配置されるように以下マニフェストファイルを変更してください。
シンプルに distype=ssdの内容に変更します。

2020-08-24 03:29 UTC, cyberblack28 commented on 13.yaml
> +    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
その方向で修正します。

2020-08-24 03:59 UTC, inductor commented on 10.yaml
> +    複数のノードからReadもWriteもアクセス可能な、800Mi以上のボリュームを要求するように以下のマニフェストファイルを変更してください。
```suggestion
    複数のノードからReadもWriteも可能で、800Mi以上のボリュームを要求するように以下のマニフェストファイルを変更してください。
```

これだったらアクセスって日本語いらない感じしますね

あとは文章のつながり的には可能な～よりも可能で～のほうが自然な感じがしました

2020-08-24 03:59 UTC, inductor commented on 8.yaml
> +    CNDT/happyというキー/値ペアを含むcndt-secretというSecret（2つ以上のKeyが書かれてる）を以下マニフェストファイルを変更して、秘密鍵CNDTの値のみを公開する環境変数を追加してください。その際、Pod内部の環境変数名としてCNDT_VARIABLEを使用してください。
1. 書かれてる、は口語表現っぽいので`書かれた`、とかにしたいけどここにこれが入ってると具体的な修飾関係がよくわからない感じになっている気がします。

2. `Secretを以下マニフェストファイルを` という日本語が変

2020-08-24 03:59 UTC, inductor commented on 9.yaml
> +    NFSを使用してcndt-pvという名前のPersistentVolumeを作成し、NFSサーバのIPを192.168.9.8、容量を8Gi、アクセスモードをRXW、Reclaim PolicyをRetain、パスが/var/lib/cndtにあることを明示するように以下マニフェストファイルに変更してください。
動詞が「～あることを明示」であれば、`容量を8Gi、アクセスモードをRXW、Reclaim PolicyをRetain`このへんの助詞は`パス`に合わせる意味でも「を」ではなく「が」にしたほうがよさそうです。

2020-08-24 04:09 UTC, MasayaAoyama requested changes

2020-08-24 04:09 UTC, MasayaAoyama commented on 7.yaml
> +    cndt-configというConfigMapを以下マニフェストファイルのPodから、/config/mapディレクトリをconfig-volumeという名前のボリュームとして複数のKey-Valueを一括でマウントするようにマニフェストファイルを変更してください。
> cndt-configというConfigMapを以下マニフェストファイルのPodから、/config/mapディレクトリをconfig-volumeという名前のボリュームとして複数のKey-Valueを一括でマウントするようにマニフェストファイルを変更してください。

ちょっと文章がわかりづらいので、例えば下記のほうが良さそうです。

cndt-configというConfigMapをconfig-volumeという名前のボリュームとしてすべてののKey-Valueを一括で/config/mapディレクトリにマウントするように、以下のPodのマニフェストファイルを変更してください。

2020-08-24 04:11 UTC, MasayaAoyama requested changes

2020-08-24 04:11 UTC, MasayaAoyama commented on 12.yaml
> +    disktype=ssdのラベルを持つノードにcndt-redisという名前のPodが配置されるように以下マニフェストファイルを変更してください。
翌々考えたらnodeAffinityも使えてしまうので、答えを一意にするためにどちらかの指定が必要そうです。

１．変更箇所は二行以内としてください　と記載する
２．base_content.yaml に nodeSelector まで書いておく

2020-08-24 04:11 UTC, inductor commented on 7.yaml
> +    cndt-configというConfigMapを以下マニフェストファイルのPodから、/config/mapディレクトリをconfig-volumeという名前のボリュームとして複数のKey-Valueを一括でマウントするようにマニフェストファイルを変更してください。
YAMLを日本語で説明するのは難しいなぁ。みつを

2020-08-24 04:12 UTC, inductor commented
ちなみにコミット見てて思ったんですがgit logとかすれば日時はわかるのでコミットメッセージに日付を書く必要はなさそう（直接関係ないですが！）

2020-08-24 04:33 UTC, cyberblack28 commented on 12.yaml
> +    disktype=ssdのラベルを持つノードにcndt-redisという名前のPodが配置されるように以下マニフェストファイルを変更してください。
2の方向で修正します。

2020-08-24 07:17 UTC, inductor commented on 9.yaml
> +    NFSを使用してcndt-pvという名前のPersistentVolumeを作成し、NFSサーバのIPを192.168.9.8、容量を8Gi、アクセスモードをRXW、Reclaim PolicyをRetain、パスを/var/lib/cndtとして以下マニフェストファイルに変更してください。
```suggestion
    NFSを使用してcndt-pvという名前のPersistentVolumeを作成し、NFSサーバのIPが192.168.9.8、容量が8Gi、アクセスモードがRXW、Reclaim PolicyがRetain、パスが/var/lib/cndtとなるように以下マニフェストファイルを変更してください。
```

`マニフェストファイルに変更してください。` だと日本語がおかしいのと、マニフェストファイルに変更を加えてくださいだと他と揃わない感じだったので。

2020-08-25 04:21 UTC, MasayaAoyama commented
lgtm

2020-08-25 04:21 UTC, merged