Add question 16 名前空間に関わる問題を追加
cloudnativedaysjp/kontest-questions pull request #3
Opened 2020-08-23 06:01 UTC by Fufuhu

ヒントを見てしまえばあっという間ですが、名前空間に関わる問題を追加してみました。

2020-08-23 20:13 UTC, MasayaAoyama requested changes

2020-08-23 20:13 UTC, MasayaAoyama commented on 16.yaml
> +    ---
ConfigMapは変更がないので、Questionの方にきさいしておいてください！

2020-08-23 20:13 UTC, MasayaAoyama commented on 16.yaml
> +    名前空間の概念の理解はKubernetesに限らずコンテナに関わる領域では非常に重要です。
名前空間だけだとなんの話だかミスリード點せそうな気もするので、Linux Namespacesって書いておいたほうが良いかもですね。（そしてここのコメントはどのみちカサレアルさんがちゃんとしたのを書いてくれますｗ）

2020-08-23 20:13 UTC, MasayaAoyama commented on 16.yaml
> +          image: nginx:latest
一応ベストプラクティスを問題にしておいたほうが良さそうなので、latestは避けておきましょうか

2020-08-25 05:27 UTC, Fufuhu commented on 16.yaml
> +    名前空間の概念の理解はKubernetesに限らずコンテナに関わる領域では非常に重要です。
あ、そうなんですね。承知しました。

2020-08-26 01:19 UTC, MasayaAoyama commented
lgtm!

2020-08-26 01:19 UTC, merged